### ISSUE TITLE
About the evaluation in the neuro-symbolic paper  

### ISSUE THREAD

**Issue by ZENGXH** [rfeinman/pyBPL#1]
Hi, 

Thanks so much for your great work. I am wondering what's the evaluation (loss function) you used in the Table1 in the neuro-symbolic paper? The NLL score looks much lower than the values in Table 3 in this paper: https://arxiv.org/abs/1603.05106 (even though the splitting is different). 

Moreover, are you planning on releasing code for the NS model? :)

Thanks!

**Comment by rfeinman** [comment]
Hi,

Thank you for your interest in our paper. We will be releasing code for the neuro-symbolic generative model sometime in the next few months after finishing a follow-up project. The reason that our log-likelihoods look different from the DeepMind paper is that they are reporting Bernoulli pixel likelihoods on the image directly, whereas our model is reporting probabilities for the latent stroke parameters. In our upcoming paper we will be reporting analogous image log-likelihoods (marginalized over latent stroke parameters).

Thanks again for the interest.

**Comment by rfeinman** [comment]
Hi @ZENGXH - we've now released the source code for our neuro-symbolic generative model: https://github.com/rfeinman/GNS-Modeling
