### ISSUE TITLE
need to pass in torch tensor

### ISSUE THREAD

**Issue by lucast4** [rfeinman/pyBPL#3]
https://github.com/rfeinman/pyBPL/blob/3e41cddfe7cb211f0d4ba4ce3bbd6d3bf5418e3d/pybpl/model/token_dist.py#L400

for this and line 569, I had to replace with tensor

**Comment by rfeinman** [comment]
Thanks for catching 👍 
Fixed in d69ddcfc1a827f9182d06ed573e18465140d7f11
